[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/img/*"
  [headers.values]
    cache-control = '''
    max-age=604800,
    public'''

[[headers]]
  for = "/*.css"
  [headers.values]
    cache-control = '''
    max-age=604800,
    public'''

[[headers]]
  for = "/*.js"
  [headers.values]
    cache-control = '''
    max-age=604800,
    public'''

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
